using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Anthropic.Models.Beta.Messages;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;

namespace ClaudeRevit.Tools;

public class CreateSection : IRevitTool
{
    public string Name => "create_section";

    public string Description =>
        "Creates a building section view from a section line in plan (start point to end point, in feet). " +
        "The section looks perpendicular to the line, to the left of the line direction. Optionally specify " +
        "vertical extent (top_ft, bottom_ft) and depth (depth_ft, how far the section sees into the model). " +
        "Defaults: 10 ft tall, starting from level 0, 30 ft deep.";

    public InputSchema InputSchema => new()
    {
        Properties = new Dictionary<string, JsonElement>
        {
            ["start_x"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Section line start X (feet)." }),
            ["start_y"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Section line start Y (feet)." }),
            ["end_x"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Section line end X (feet)." }),
            ["end_y"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Section line end Y (feet)." }),
            ["bottom_ft"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Bottom Z of section box in feet (default 0)." }),
            ["top_ft"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Top Z of section box in feet (default 10)." }),
            ["depth_ft"] = JsonSerializer.SerializeToElement(new { type = "number", description = "How far the section sees into the model in feet (default 30)." }),
            ["name"] = JsonSerializer.SerializeToElement(new { type = "string", description = "Optional section view name." })
        },
        Required = ["start_x", "start_y", "end_x", "end_y"]
    };

    public bool RequiresTransaction => true;

    public string Execute(IReadOnlyDictionary<string, JsonElement> input, UIApplication app)
    {
        var doc = app.ActiveUIDocument?.Document
            ?? throw new InvalidOperationException("No document is open.");

        var sx = input["start_x"].GetDouble();
        var sy = input["start_y"].GetDouble();
        var ex = input["end_x"].GetDouble();
        var ey = input["end_y"].GetDouble();
        var bottom = input.TryGetValue("bottom_ft", out var b) ? b.GetDouble() : 0.0;
        var top = input.TryGetValue("top_ft", out var t) ? t.GetDouble() : 10.0;
        var depth = input.TryGetValue("depth_ft", out var d) ? d.GetDouble() : 30.0;

        if (top <= bottom)
            throw new InvalidOperationException("top_ft must be greater than bottom_ft.");

        var start = new XYZ(sx, sy, 0);
        var end = new XYZ(ex, ey, 0);
        if (start.IsAlmostEqualTo(end))
            throw new InvalidOperationException("Section line has zero length.");

        var sectionTypeId = new FilteredElementCollector(doc)
            .OfClass(typeof(ViewFamilyType)).Cast<ViewFamilyType>()
            .FirstOrDefault(vft => vft.ViewFamily == ViewFamily.Section)?.Id
            ?? throw new InvalidOperationException("No Section ViewFamilyType in this document.");

        var midpoint = (start + end) * 0.5;
        var lineLength = (end - start).GetLength();

        // BasisX runs along the section line (left-to-right in the view)
        var basisX = (end - start).Normalize();
        var basisY = XYZ.BasisZ;
        // BasisZ points OUT of the page (toward viewer, away from what we see)
        // Section convention: we look in -BasisZ direction. To look "to the left of the line direction",
        // we want BasisZ = basisY × basisX (right-hand rule perpendicular pointing right of line)
        var basisZ = basisX.CrossProduct(basisY);

        var transform = Transform.Identity;
        transform.Origin = new XYZ(midpoint.X, midpoint.Y, (top + bottom) / 2);
        transform.BasisX = basisX;
        transform.BasisY = basisY;
        transform.BasisZ = basisZ;

        var bbox = new BoundingBoxXYZ
        {
            Transform = transform,
            Min = new XYZ(-lineLength / 2, -(top - bottom) / 2, 0),
            Max = new XYZ(lineLength / 2, (top - bottom) / 2, depth)
        };

        var section = ViewSection.CreateSection(doc, sectionTypeId, bbox);

        if (input.TryGetValue("name", out var n) && n.ValueKind == JsonValueKind.String)
        {
            try { section.Name = n.GetString(); }
            catch { /* name conflict — keep autogenerated */ }
        }

        return JsonSerializer.Serialize(new
        {
            id = section.Id.Value,
            type = "Section",
            name = section.Name,
            line_length_ft = lineLength,
            depth_ft = depth,
            extent_ft = new { bottom, top }
        });
    }
}
