using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Anthropic.Models.Beta.Messages;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;

namespace ClaudeRevit.Tools;

public class CreateElevation : IRevitTool
{
    public string Name => "create_elevation";

    public string Description =>
        "Creates an elevation marker in a parent floor plan view, then generates an elevation view in the " +
        "given direction ('north', 'south', 'east', or 'west'). Position is in plan coordinates, in feet. " +
        "Defaults: parent view = active view if it's a plan; scale = 100.";

    public InputSchema InputSchema => new()
    {
        Properties = new Dictionary<string, JsonElement>
        {
            ["x"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Marker X position (feet)." }),
            ["y"] = JsonSerializer.SerializeToElement(new { type = "number", description = "Marker Y position (feet)." }),
            ["direction"] = JsonSerializer.SerializeToElement(new
            {
                type = "string",
                description = "Look direction.",
                @enum = new[] { "north", "south", "east", "west" }
            }),
            ["parent_view_id"] = JsonSerializer.SerializeToElement(new { type = "integer", description = "Optional plan view id to host the marker. Defaults to active view." }),
            ["scale"] = JsonSerializer.SerializeToElement(new { type = "integer", description = "View scale denominator (default 100)." }),
            ["name"] = JsonSerializer.SerializeToElement(new { type = "string", description = "Optional elevation view name." })
        },
        Required = ["x", "y", "direction"]
    };

    public bool RequiresTransaction => true;

    public string Execute(IReadOnlyDictionary<string, JsonElement> input, UIApplication app)
    {
        var doc = app.ActiveUIDocument?.Document
            ?? throw new InvalidOperationException("No document is open.");

        var x = input["x"].GetDouble();
        var y = input["y"].GetDouble();
        var direction = input["direction"].GetString()!.ToLowerInvariant();
        var scale = input.TryGetValue("scale", out var s) ? s.GetInt32() : 100;

        // Standard elevation marker indices: 0=south, 1=east, 2=north, 3=west
        // (Revit's default ElevationMarker layout is 4 elevations, indexed clockwise from south)
        var index = direction switch
        {
            "south" => 0,
            "east" => 1,
            "north" => 2,
            "west" => 3,
            _ => throw new InvalidOperationException(
                $"Unknown direction '{direction}'. Use 'north', 'south', 'east', or 'west'.")
        };

        ViewPlan parentPlan;
        if (input.TryGetValue("parent_view_id", out var pv) && pv.ValueKind == JsonValueKind.Number)
        {
            parentPlan = doc.GetElement(new ElementId(pv.GetInt64())) as ViewPlan
                ?? throw new InvalidOperationException("parent_view_id is not a plan view.");
        }
        else
        {
            parentPlan = doc.ActiveView as ViewPlan
                ?? throw new InvalidOperationException(
                    "Active view is not a plan. Specify parent_view_id or activate a plan view first.");
        }

        var elevationTypeId = new FilteredElementCollector(doc)
            .OfClass(typeof(ViewFamilyType)).Cast<ViewFamilyType>()
            .FirstOrDefault(vft => vft.ViewFamily == ViewFamily.Elevation)?.Id
            ?? throw new InvalidOperationException("No Elevation ViewFamilyType in this document.");

        var marker = ElevationMarker.CreateElevationMarker(doc, elevationTypeId, new XYZ(x, y, 0), scale);
        var view = marker.CreateElevation(doc, parentPlan.Id, index);

        if (input.TryGetValue("name", out var n) && n.ValueKind == JsonValueKind.String)
        {
            try { view.Name = n.GetString(); }
            catch { /* name conflict — keep autogenerated */ }
        }

        return JsonSerializer.Serialize(new
        {
            marker_id = marker.Id.Value,
            view_id = view.Id.Value,
            type = "Elevation",
            direction,
            name = view.Name,
            parent_view = parentPlan.Name
        });
    }
}
